apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: mediawiki-mysql
type: Opaque
data:
  root-password: {{ .Values.db.rootPassword | b64enc | quote }}
  mediawiki-username: {{ .Values.db.mediawikiUsername | b64enc | quote }}
  mediawiki-password: {{ .Values.db.mediawikiPassword | b64enc | quote }}