apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-mediawiki-secret"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: mediawiki-webserver
type: Opaque
data:
  mediawiki-user: {{ .Values.mediawiki.admin.username | b64enc | quote }}
  mediawiki-db-user: {{ .Values.db.mediawikiUsername | b64enc | quote }}
  mediawiki-password: {{ .Values.mediawiki.admin.password | b64enc | quote }}
  mediawiki-db-password: {{ .Values.db.mediawikiPassword | b64enc | quote }}
  mediawiki-secret-key: {{ .Values.mediawiki.secretkey | b64enc | quote }}
  mediawiki-upgrade-key: {{ .Values.mediawiki.upgradekey  | b64enc | quote }}