apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mediawiki-svc
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: mediawiki-webserver
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: mediawiki-webserver
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30001
